In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [2]:
transactions = [
    ["Bread", "Milk", "Butter"],
    ["Bread", "Butter"],
    ["Milk", "Eggs"],
    ["Bread", "Milk", "Diaper"],
    ["Milk", "Diaper", "Beer"],
    ["Bread", "Butter", "Milk"],
    ["Butter", "Diaper"],
    ["Bread", "Beer"],
    ["Milk", "Eggs", "Bread"],
    ["Bread", "Milk", "Butter"]
]

In [3]:
data = pd.DataFrame(transactions)
data.head()

       0       1       2
0  Bread    Milk  Butter
1  Bread  Butter    None
2   Milk    Eggs    None
3  Bread    Milk  Diaper
4   Milk  Diaper    Beer

In [4]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [5]:
print("--- One-Hot Encoded DataFrame ---")
df.head()

--- One-Hot Encoded DataFrame ---

    Beer  Bread  Butter  Diaper   Eggs   Milk
0  False   True    True   False  False   True
1  False   True    True   False  False  False
2  False  False   False   False   True   True
3  False   True   False    True  False   True
4   True  False   False    True  False   True

In [6]:
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

In [7]:
print("--- Frequent Itemsets (min_support=0.2) ---")
frequent_itemsets.head()

--- Frequent Itemsets (min_support=0.2) ---

   support  itemsets
0      0.2    (Beer)
1      0.7   (Bread)
2      0.5  (Butter)
3      0.3  (Diaper)
4      0.2    (Eggs)