In [2]:
li = ["Department of Software Engineeering in faculty of Computing",
      "Department of Data Science in faculty of Computing",
      "Department of Computing and Information Systems in faculty of Computing"]

dic = {}
for i in li:
  for key in i.split():
    if key in dic:
      dic[key] += 1
    else:
      dic[key] = 1

print(dic)

{'Department': 3, 'of': 6, 'Software': 1, 'Engineeering': 1, 'in': 3, 'faculty': 3, 'Computing': 4, 'Data': 1, 'Science': 1, 'and': 1, 'Information': 1, 'Systems': 1}

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(li)
print(result)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 22 stored elements and shape (3, 12)>
  Coords	Values
  (0, 3)	0.269841950301669
  (0, 8)	0.539683900603338
  (0, 10)	0.45688213735006783
  (0, 4)	0.45688213735006783
  (0, 6)	0.269841950301669
  (0, 5)	0.269841950301669
  (0, 1)	0.269841950301669
  (1, 3)	0.2698419503016691
  (1, 8)	0.5396839006033382
  (1, 6)	0.2698419503016691
  (1, 5)	0.2698419503016691
  (1, 1)	0.2698419503016691
  (1, 2)	0.4568821373500679
  (1, 9)	0.4568821373500679
  (2, 3)	0.2258755805737144
  (2, 8)	0.4517511611474288
  (2, 6)	0.2258755805737144
  (2, 5)	0.2258755805737144
  (2, 1)	0.4517511611474288
  (2, 0)	0.3824406024057253
  (2, 7)	0.3824406024057253
  (2, 11)	0.3824406024057253

In [8]:
feature_names = tfidf.get_feature_names_out()
print(feature_names)

['and' 'computing' 'data' 'department' 'engineeering' 'faculty' 'in'
 'information' 'of' 'science' 'software' 'systems']

In [10]:
df_tfidf = pd.DataFrame(result.toarray(), columns=feature_names)
df_tfidf.round(3)

     and  computing   data  department  ...     of  science  software  systems
0  0.000      0.270  0.000       0.270  ...  0.540    0.000     0.457    0.000
1  0.000      0.270  0.457       0.270  ...  0.540    0.457     0.000    0.000
2  0.382      0.452  0.000       0.226  ...  0.452    0.000     0.000    0.382

[3 rows x 12 columns]

In [ ]:
file_path = 'your_file.txt'

try:
    # Open the file in read mode ('r') with automatic closing
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
        print(content)
except FileNotFoundError:
    print(f"File '{file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [22]:
file_paths = ['/content/doc1_ai.txt', '/content/doc2_cloud.txt', '/content/doc3_security.txt']

file_contents = []

for file_path in file_paths:
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            file_contents.append(content)
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
    except Exception as e:
        print(f"An error occurred while reading '{file_path}': {e}")

print(file_contents)

['Artificial intelligence is changing the world. Robots use artificial intelligence to learn and solve complex problems. The future of technology depends on artificial intelligence.', 'Cloud computing allows us to store massive amounts of data. Data science uses this data to predict future trends. The future of data storage is in the cloud.', 'Cybersecurity protects our networks from hackers. Strong passwords and encryption are essential for cybersecurity. The future of internet safety requires advanced cybersecurity.']

In [23]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [25]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [26]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

for text in file_contents:
  words = word_tokenize(text.lower())

  filtered_sentence = [word for word in words if word not in stop_words]

  print("Original Tokens:", words)
  print("Filtered Tokens:", filtered_sentence)
  print("\n")

Original Tokens: ['artificial', 'intelligence', 'is', 'changing', 'the', 'world', '.', 'robots', 'use', 'artificial', 'intelligence', 'to', 'learn', 'and', 'solve', 'complex', 'problems', '.', 'the', 'future', 'of', 'technology', 'depends', 'on', 'artificial', 'intelligence', '.']
Filtered Tokens: ['artificial', 'intelligence', 'changing', 'world', '.', 'robots', 'use', 'artificial', 'intelligence', 'learn', 'solve', 'complex', 'problems', '.', 'future', 'technology', 'depends', 'artificial', 'intelligence', '.']


Original Tokens: ['cloud', 'computing', 'allows', 'us', 'to', 'store', 'massive', 'amounts', 'of', 'data', '.', 'data', 'science', 'uses', 'this', 'data', 'to', 'predict', 'future', 'trends', '.', 'the', 'future', 'of', 'data', 'storage', 'is', 'in', 'the', 'cloud', '.']
Filtered Tokens: ['cloud', 'computing', 'allows', 'us', 'store', 'massive', 'amounts', 'data', '.', 'data', 'science', 'uses', 'data', 'predict', 'future', 'trends', '.', 'future', 'data', 'storage', 'cloud', '.']


Original Tokens: ['cybersecurity', 'protects', 'our', 'networks', 'from', 'hackers', '.', 'strong', 'passwords', 'and', 'encryption', 'are', 'essential', 'for', 'cybersecurity', '.', 'the', 'future', 'of', 'internet', 'safety', 'requires', 'advanced', 'cybersecurity', '.']
Filtered Tokens: ['cybersecurity', 'protects', 'networks', 'hackers', '.', 'strong', 'passwords', 'encryption', 'essential', 'cybersecurity', '.', 'future', 'internet', 'safety', 'requires', 'advanced', 'cybersecurity', '.']

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_files = TfidfVectorizer()
result_files = tfidf_files.fit_transform(file_contents)

feature_names_files = tfidf_files.get_feature_names_out()
df_tfidf_files = pd.DataFrame(result_files.toarray(), columns=feature_names_files)

display(df_tfidf_files.round(3))

   advanced  allows  amounts    and    are  ...  trends     us    use   uses  world
0     0.000   0.000    0.000  0.133  0.000  ...   0.000  0.000  0.175  0.000  0.175
1     0.000   0.158    0.158  0.000  0.000  ...   0.158  0.158  0.000  0.158  0.000
2     0.198   0.000    0.000  0.150  0.198  ...   0.000  0.000  0.000  0.000  0.000

[3 rows x 50 columns]

In [29]:
file_paths = ['/content/doc1_ai.txt', '/content/doc2_cloud.txt', '/content/doc3_security.txt']

file_contents = []

for file_path in file_paths:
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            file_contents.append(content)
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
    except Exception as e:
        print(f"An error occurred while reading '{file_path}': {e}")


from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_files = TfidfVectorizer(stop_words="english")
result_files = tfidf_files.fit_transform(file_contents)

feature_names_files = tfidf_files.get_feature_names_out()
df_tfidf_files = pd.DataFrame(result_files.toarray(), columns=feature_names_files)

display(df_tfidf_files.round(3))

   advanced  allows  amounts  artificial  ...  trends    use   uses  world
0     0.000   0.000    0.000       0.563  ...   0.000  0.188  0.000  0.188
1     0.000   0.178    0.178       0.000  ...   0.178  0.000  0.178  0.000
2     0.222   0.000    0.000       0.000  ...   0.000  0.000  0.000  0.000

[3 rows x 37 columns]

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

data = pd.read_csv("/content/data_for_preprocessing.csv")

data.head()

   Unnamed: 0                                               Text Author
0           0  This study investigates the chemical compositi...     AI
1           1  This study explores the cultural history of oi...     AI
2           2   Isolation of human peripheral blood mononucle...  Human
3           3   Dynamic Bayesian Networks (DBNs) are probabil...  Human
4           4   Within volleyball, performance analysis is em...  Human

In [36]:
data.shape

(6069, 3)

In [37]:
content = [x for x in data["Text"]]
len(content)

6069

In [44]:
content[1]

'This study explores the cultural history of oil wrestling in Kırkpınar, analyzing its status as an intangible cultural heritage and its modern organization.'

In [46]:
import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def clean_and_lemmatize(text):
    text = re.sub(r'[^a-zA-Z\s]', '', text.lower())

    words = [lemmatizer.lemmatize(word) for word in text.split() if len(word) > 2]

    return " ".join(words)

cleaned_content = [clean_and_lemmatize(doc) for doc in content]

tfidf_files = TfidfVectorizer(stop_words="english")
result_files = tfidf_files.fit_transform(cleaned_content)

feature_names_files = tfidf_files.get_feature_names_out()
df_tfidf_files = pd.DataFrame(result_files.toarray(), columns=feature_names_files)

df_tfidf_files.head(10)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

   aaa  aaap  aac  aacgtt  ...  zvadfmk  zwitterionic  zygosaccharomyces  zymomonas
0  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
1  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
2  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
3  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
4  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
5  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
6  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
7  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
8  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0
9  0.0   0.0  0.0     0.0  ...      0.0           0.0                0.0        0.0

[10 rows x 39252 columns]

In [47]:
import nltk
from nltk.corpus import words
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

nltk.download('words')
english_vocab = set(w.lower() for w in words.words())

def remove_gibberish(text):
    tokens = text.lower().split()
    real_words = [w for w in tokens if w in english_vocab and len(w) > 2]
    return " ".join(real_words)

meaningful_content = [remove_gibberish(doc) for doc in content]

# 3. Re-run your TF-IDF
tfidf_files = TfidfVectorizer(stop_words="english")
result_files = tfidf_files.fit_transform(meaningful_content)

# 4. Create the clean DataFrame
feature_names_files = tfidf_files.get_feature_names_out()
df_tfidf_files = pd.DataFrame(result_files.toarray(), columns=feature_names_files)

print(f"Original columns: {len(feature_names_files)}")
df_tfidf_files.head(10)

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

Original columns: 13147

   abandoned  abandonment  abatement  ...  zoonotic  zostera  zygosaccharomyces
0        0.0          0.0        0.0  ...       0.0      0.0                0.0
1        0.0          0.0        0.0  ...       0.0      0.0                0.0
2        0.0          0.0        0.0  ...       0.0      0.0                0.0
3        0.0          0.0        0.0  ...       0.0      0.0                0.0
4        0.0          0.0        0.0  ...       0.0      0.0                0.0
5        0.0          0.0        0.0  ...       0.0      0.0                0.0
6        0.0          0.0        0.0  ...       0.0      0.0                0.0
7        0.0          0.0        0.0  ...       0.0      0.0                0.0
8        0.0          0.0        0.0  ...       0.0      0.0                0.0
9        0.0          0.0        0.0  ...       0.0      0.0                0.0

[10 rows x 13147 columns]

In [49]:
df_tfidf_files.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Columns: 13147 entries, abandoned to zygosaccharomyces
dtypes: float64(13147)
memory usage: 608.7 MB

In [48]:
output_csv_path = 'tfidf_features.csv'
df_tfidf_files.to_csv(output_csv_path, index=False)
print(f"DataFrame successfully saved to {output_csv_path}")

DataFrame successfully saved to tfidf_features.csv