In [33]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [34]:
transactions = [
    ["Bread", "Milk", "Butter"],
    ["Bread", "Butter"],
    ["Milk", "Eggs"],
    ["Bread", "Milk", "Diaper"],
    ["Milk", "Diaper", "Beer"],
    ["Bread", "Butter", "Milk"],
    ["Butter", "Diaper"],
    ["Bread", "Beer"],
    ["Milk", "Eggs", "Bread"],
    ["Bread", "Milk", "Butter"]
]

In [35]:
te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [36]:
print("--- One-Hot Encoded DataFrame ---")
df

--- One-Hot Encoded DataFrame ---

    Beer  Bread  Butter  Diaper   Eggs   Milk
0  False   True    True   False  False   True
1  False   True    True   False  False  False
2  False  False   False   False   True   True
3  False   True   False    True  False   True
4   True  False   False    True  False   True
5  False   True    True   False  False   True
6  False  False    True    True  False  False
7   True   True   False   False  False  False
8  False   True   False   False   True   True
9  False   True    True   False  False   True

In [37]:
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)
print("--- Frequent Itemsets (min_support=0.2) ---")
frequent_itemsets

--- Frequent Itemsets (min_support=0.2) ---

    support               itemsets
0       0.2                 (Beer)
1       0.7                (Bread)
2       0.5               (Butter)
3       0.3               (Diaper)
4       0.2                 (Eggs)
5       0.7                 (Milk)
6       0.4        (Bread, Butter)
7       0.5          (Milk, Bread)
8       0.3         (Milk, Butter)
9       0.2         (Diaper, Milk)
10      0.2           (Eggs, Milk)
11      0.3  (Milk, Bread, Butter)

In [38]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

        antecedents      consequents  support  confidence      lift
0           (Bread)         (Butter)      0.4    0.571429  1.142857
1          (Butter)          (Bread)      0.4    0.800000  1.142857
2           (Bread)           (Milk)      0.5    0.714286  1.020408
3            (Milk)          (Bread)      0.5    0.714286  1.020408
4            (Eggs)           (Milk)      0.2    1.000000  1.428571
5            (Milk)           (Eggs)      0.2    0.285714  1.428571
6     (Milk, Bread)         (Butter)      0.3    0.600000  1.200000
7   (Bread, Butter)           (Milk)      0.3    0.750000  1.071429
8    (Milk, Butter)          (Bread)      0.3    1.000000  1.428571
9           (Bread)   (Milk, Butter)      0.3    0.428571  1.428571
10           (Milk)  (Bread, Butter)      0.3    0.428571  1.071429
11         (Butter)    (Milk, Bread)      0.3    0.600000  1.200000